BACKPORT: FROMGIT: mm: filemap: Fix microblaze build failure with 'mmu_defconfig'
Commit f9ce0be71d1f ("mm: Cleanup faultaround and finish_fault()
codepaths") added a call to 'update_mmu_cache()' in mm/filemap.c, which
breaks the build for microblaze:

  | mm/filemap.c: In function 'filemap_map_pages':
  | mm/filemap.c:3153:3: error: implicit declaration of function 'update_mmu_cache'; did you mean 'update_mmu_tlb'?

Include asm/tlbflush.h in mm/filemap.c to make sure that the function
(or indeed, macro) is available.

Reported-by: Guenter Roeck <linux@roeck-us.net>
Tested-by: Guenter Roeck <linux@roeck-us.net>
Link: https://lore.kernel.org/r/20210209202449.GA104837@roeck-us.net
Signed-off-by: Will Deacon <will@kernel.org>
Change-Id: I5a3bdb285a909de6361f751c82eb347ddfb0cdee
Bug: 171278850
(cherry picked from commit de591a82f41b61af4a8fce49d21b43105c5c218
https://git.kernel.org/pub/scm/linux/kernel/git/arm64/linux.git/log/?h=for-next/faultaround)
Signed-off-by: Vinayak Menon <vinmenon@codeaurora.org>
Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>